#!/bin/bash

docker compose up students-api-python-db -d

export DB_HOST="localhost:6657"
export DB_USERNAME=student_user
export DB_PASSWORD=student_password

alembic upgrade head

uvicorn main:app --reload
