version: "3.9"
services:
  students-api-python-db:
    image: postgres:13.1
    container_name: students-api-python-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ${PWD}/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6657:5432"
    expose:
      - 6657

  students-api-python:
    depends_on:
      - students-api-python-db
    build:
      context: .
    container_name: students-api-python
    environment:
      DB_HOST: "docker.for.mac.localhost:6657"
      DB_USERNAME: student_user
      DB_PASSWORD: student_password
    ports:
      - "8620:80"
    expose:
      - 8620
